module.exports = {
  printWidth: 80,
  tabWidth: 2,
  useTabs: false,
  semi: false,
  singleQuote: true,
  quoteProps: 'as-needed',
  jsxSingleQuote: false,
  trailingComma: 'es5',
  bracketSpacing: true,
  arrowParens: 'always',
  endOfLine: 'auto',
  plugins: [
    require.resolve('@trivago/prettier-plugin-sort-imports'),
    'prettier-plugin-tailwindcss',
  ],
  tailwindFunctions: ['tv'],
  importOrder: [
    '^@mui',
    '^components/(.*)$',
    '^views/(.*)$',
    '^utils/(.*)$',
    '^services/(.*)$',
    '^assets/(.*)$',
    '^config/(.*)$',
    '^messages/(.*)$',
    '^styles/(.*)$',
    '^@remix/(.*)$',
    '^[~/]',
    '^/images/(.*)$',
    '^[../]',
    '^[./]',
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
}
